# The Data Source Name for the database
# Make sure you override this in production with the environment variable: RESTFUL_DSN
dsn: "mongodb://mongodb:27017/"
db_name: proofdex

rabbitmq: amqp://guest:guest@rabbitmq:5672/
redis: redis://redis:6379

ethereum:
  url: http://localhost:8545
  exchange_address: "0xfc074fd5702e6becb78d64acd4126a0079f42d85"
  weth_address: "0x2EB24432177e82907dE24b7c5a6E0a5c03226135"
  fee_account: "0xe8e84ee367bc63ddb38d3d01bccef106c194dc47"
  decimal: 8

tick_duration:
    sec: [5, 30]
    min: [1, 5, 15]
    hour: [1]
    day: [1]
    week: [1]
    month: [1, 3, 6, 9]
    year: [1]

# These are secret keys used for JWT signing and verification.
# Make sure you override these keys in production by the following environment variables:
#   RESTFUL_JWT_VERIFICATION_KEY
#   RESTFUL_JWT_SIGNING_KEY
jwt_verification_key: "QfCAH04Cob7b71QCqy738vw5XGSnFZ9d"
jwt_signing_key: "QfCAH04Cob7b71QCqy738vw5XGSnFZ9d"
# Uncomment the following line and set an appropriate JWT signing method, if needed
# The default signing method is HS256.
#jwt_signing_method: "HS256"